export const FILAMENT_CATALOG = [
  // ─── BAMBU LAB — PLA Basic ───────────────────────────────────────────────
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Bambu White',       color_hex: '#F2F0ED', notes: 'PLA Basic' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Bambu Black',       color_hex: '#1C1C1C', notes: 'PLA Basic' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Bambu Grey',        color_hex: '#888888', notes: 'PLA Basic' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Bambu Dark Grey',   color_hex: '#3A3A3A', notes: 'PLA Basic' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Bambu Red',         color_hex: '#CC2222', notes: 'PLA Basic' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Bambu Orange',      color_hex: '#E85B0A', notes: 'PLA Basic' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Bambu Yellow',      color_hex: '#F5C800', notes: 'PLA Basic' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Bambu Green',       color_hex: '#2E8B1A', notes: 'PLA Basic' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Bambu Jade Green',  color_hex: '#47B882', notes: 'PLA Basic' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Bambu Blue',        color_hex: '#1C5FAD', notes: 'PLA Basic' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Bambu Navy Blue',   color_hex: '#1A2E6E', notes: 'PLA Basic' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Bambu Purple',      color_hex: '#6633CC', notes: 'PLA Basic' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Bambu Pink',        color_hex: '#E8558A', notes: 'PLA Basic' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Bambu Brown',       color_hex: '#7B4A2D', notes: 'PLA Basic' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Bambu Beige',       color_hex: '#D4C4A0', notes: 'PLA Basic' },
  // Bambu PLA Matte
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Matte White',       color_hex: '#F0EDE8', notes: 'PLA Matte' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Matte Black',       color_hex: '#222222', notes: 'PLA Matte' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Matte Grey',        color_hex: '#8C8C8C', notes: 'PLA Matte' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Matte Red',         color_hex: '#C0392B', notes: 'PLA Matte' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Matte Blue',        color_hex: '#2E4FAD', notes: 'PLA Matte' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Matte Green',       color_hex: '#3A7A45', notes: 'PLA Matte' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Matte Yellow',      color_hex: '#D4AE00', notes: 'PLA Matte' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Matte Orange',      color_hex: '#D4591A', notes: 'PLA Matte' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Matte Pink',        color_hex: '#CC5577', notes: 'PLA Matte' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Matte Purple',      color_hex: '#5C3399', notes: 'PLA Matte' },
  // Bambu PLA Silk
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Silk Gold',         color_hex: '#D4A842', notes: 'PLA Silk' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Silk Silver',       color_hex: '#C0C0C8', notes: 'PLA Silk' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Silk Copper',       color_hex: '#B87333', notes: 'PLA Silk' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Silk Red',          color_hex: '#CC2244', notes: 'PLA Silk' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Silk Blue',         color_hex: '#1A44AA', notes: 'PLA Silk' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Silk Green',        color_hex: '#1A7A44', notes: 'PLA Silk' },
  // Bambu PETG
  { brand: 'Bambu Lab', material: 'PETG', color_name: 'PETG White',       color_hex: '#F0EDE8', notes: 'PETG Basic' },
  { brand: 'Bambu Lab', material: 'PETG', color_name: 'PETG Black',       color_hex: '#1A1A1A', notes: 'PETG Basic' },
  { brand: 'Bambu Lab', material: 'PETG', color_name: 'PETG Grey',        color_hex: '#7A7A7A', notes: 'PETG Basic' },
  { brand: 'Bambu Lab', material: 'PETG', color_name: 'PETG Red',         color_hex: '#CC2222', notes: 'PETG Basic' },
  { brand: 'Bambu Lab', material: 'PETG', color_name: 'PETG Blue',        color_hex: '#1C5FAD', notes: 'PETG Basic' },
  { brand: 'Bambu Lab', material: 'PETG', color_name: 'PETG Green',       color_hex: '#2E8B1A', notes: 'PETG Basic' },
  { brand: 'Bambu Lab', material: 'PETG', color_name: 'PETG Yellow',      color_hex: '#F5C800', notes: 'PETG Basic' },
  { brand: 'Bambu Lab', material: 'PETG', color_name: 'PETG Orange',      color_hex: '#E8700A', notes: 'PETG Basic' },
  { brand: 'Bambu Lab', material: 'PETG', color_name: 'PETG Transparent', color_hex: '#D0E8F0', notes: 'PETG Basic' },
  // Bambu ABS
  { brand: 'Bambu Lab', material: 'ABS', color_name: 'ABS White',         color_hex: '#F0EDE8', notes: 'ABS' },
  { brand: 'Bambu Lab', material: 'ABS', color_name: 'ABS Black',         color_hex: '#1A1A1A', notes: 'ABS' },
  { brand: 'Bambu Lab', material: 'ABS', color_name: 'ABS Grey',          color_hex: '#7A7A7A', notes: 'ABS' },
  { brand: 'Bambu Lab', material: 'ABS', color_name: 'ABS Red',           color_hex: '#CC2222', notes: 'ABS' },
  { brand: 'Bambu Lab', material: 'ABS', color_name: 'ABS Blue',          color_hex: '#1C5FAD', notes: 'ABS' },
  { brand: 'Bambu Lab', material: 'ABS', color_name: 'ABS Green',         color_hex: '#2E8B1A', notes: 'ABS' },
  // Bambu TPU
  { brand: 'Bambu Lab', material: 'TPU', color_name: 'TPU White',         color_hex: '#F0EDE8', notes: 'TPU 95A' },
  { brand: 'Bambu Lab', material: 'TPU', color_name: 'TPU Black',         color_hex: '#1A1A1A', notes: 'TPU 95A' },
  { brand: 'Bambu Lab', material: 'TPU', color_name: 'TPU Grey',          color_hex: '#7A7A7A', notes: 'TPU 95A' },
  { brand: 'Bambu Lab', material: 'TPU', color_name: 'TPU Red',           color_hex: '#CC2222', notes: 'TPU 95A' },
  { brand: 'Bambu Lab', material: 'TPU', color_name: 'TPU Blue',          color_hex: '#1C5FAD', notes: 'TPU 95A' },
  { brand: 'Bambu Lab', material: 'TPU', color_name: 'TPU Yellow',        color_hex: '#F5C800', notes: 'TPU 95A' },
  { brand: 'Bambu Lab', material: 'TPU', color_name: 'TPU Transparent',   color_hex: '#D8EEF8', notes: 'TPU 95A' },

  // ─── SUNLU — PLA+ ────────────────────────────────────────────────────────
  { brand: 'Sunlu', material: 'PLA', color_name: 'Sunlu White',           color_hex: '#F5F2ED', notes: 'PLA+' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Sunlu Black',           color_hex: '#1A1A1A', notes: 'PLA+' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Sunlu Grey',            color_hex: '#8C8C8C', notes: 'PLA+' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Sunlu Dark Grey',       color_hex: '#404040', notes: 'PLA+' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Sunlu Red',             color_hex: '#CC2222', notes: 'PLA+' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Sunlu Orange',          color_hex: '#E8700A', notes: 'PLA+' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Sunlu Yellow',          color_hex: '#F5C800', notes: 'PLA+' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Sunlu Green',           color_hex: '#2E8B1A', notes: 'PLA+' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Sunlu Army Green',      color_hex: '#4A6A2A', notes: 'PLA+' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Sunlu Blue',            color_hex: '#1C5FAD', notes: 'PLA+' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Sunlu Navy Blue',       color_hex: '#1A2E6E', notes: 'PLA+' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Sunlu Purple',          color_hex: '#6633CC', notes: 'PLA+' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Sunlu Pink',            color_hex: '#E8558A', notes: 'PLA+' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Sunlu Brown',           color_hex: '#7B4A2D', notes: 'PLA+' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Sunlu Skin',            color_hex: '#E8C8A0', notes: 'PLA+' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Sunlu Transparent',     color_hex: '#D8EEF8', notes: 'PLA+' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Sunlu Glow Green',      color_hex: '#A0D080', notes: 'PLA+ świecący' },
  // Sunlu Silk PLA
  { brand: 'Sunlu', material: 'PLA', color_name: 'Silk Gold',             color_hex: '#D4A842', notes: 'PLA Silk' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Silk Silver',           color_hex: '#C0C0C8', notes: 'PLA Silk' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Silk Copper',           color_hex: '#B87333', notes: 'PLA Silk' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Silk Red',              color_hex: '#CC2244', notes: 'PLA Silk' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Silk Blue',             color_hex: '#1A44AA', notes: 'PLA Silk' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Silk Purple',           color_hex: '#6633CC', notes: 'PLA Silk' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Silk Dual Rainbow',     color_hex: '#AA44AA', notes: 'PLA Silk Dual' },
  // Sunlu PETG
  { brand: 'Sunlu', material: 'PETG', color_name: 'PETG White',           color_hex: '#F0EDE8', notes: 'PETG' },
  { brand: 'Sunlu', material: 'PETG', color_name: 'PETG Black',           color_hex: '#1A1A1A', notes: 'PETG' },
  { brand: 'Sunlu', material: 'PETG', color_name: 'PETG Grey',            color_hex: '#7A7A7A', notes: 'PETG' },
  { brand: 'Sunlu', material: 'PETG', color_name: 'PETG Red',             color_hex: '#CC2222', notes: 'PETG' },
  { brand: 'Sunlu', material: 'PETG', color_name: 'PETG Blue',            color_hex: '#1C5FAD', notes: 'PETG' },
  { brand: 'Sunlu', material: 'PETG', color_name: 'PETG Green',           color_hex: '#2E8B1A', notes: 'PETG' },
  { brand: 'Sunlu', material: 'PETG', color_name: 'PETG Yellow',          color_hex: '#F5C800', notes: 'PETG' },
  { brand: 'Sunlu', material: 'PETG', color_name: 'PETG Orange',          color_hex: '#E8700A', notes: 'PETG' },
  { brand: 'Sunlu', material: 'PETG', color_name: 'PETG Transparent',     color_hex: '#D0E8F0', notes: 'PETG' },
  // Sunlu ABS
  { brand: 'Sunlu', material: 'ABS', color_name: 'ABS White',             color_hex: '#F0EDE8', notes: 'ABS' },
  { brand: 'Sunlu', material: 'ABS', color_name: 'ABS Black',             color_hex: '#1A1A1A', notes: 'ABS' },
  { brand: 'Sunlu', material: 'ABS', color_name: 'ABS Grey',              color_hex: '#7A7A7A', notes: 'ABS' },
  { brand: 'Sunlu', material: 'ABS', color_name: 'ABS Red',               color_hex: '#CC2222', notes: 'ABS' },
  { brand: 'Sunlu', material: 'ABS', color_name: 'ABS Blue',              color_hex: '#1C5FAD', notes: 'ABS' },
  { brand: 'Sunlu', material: 'ABS', color_name: 'ABS Green',             color_hex: '#2E8B1A', notes: 'ABS' },
  // Sunlu TPU
  { brand: 'Sunlu', material: 'TPU', color_name: 'TPU White',             color_hex: '#F0EDE8', notes: 'TPU 95A' },
  { brand: 'Sunlu', material: 'TPU', color_name: 'TPU Black',             color_hex: '#1A1A1A', notes: 'TPU 95A' },
  { brand: 'Sunlu', material: 'TPU', color_name: 'TPU Grey',              color_hex: '#7A7A7A', notes: 'TPU 95A' },
  { brand: 'Sunlu', material: 'TPU', color_name: 'TPU Red',               color_hex: '#CC2222', notes: 'TPU 95A' },
  { brand: 'Sunlu', material: 'TPU', color_name: 'TPU Blue',              color_hex: '#1C5FAD', notes: 'TPU 95A' },
  { brand: 'Sunlu', material: 'TPU', color_name: 'TPU Yellow',            color_hex: '#F5C800', notes: 'TPU 95A' },
  { brand: 'Sunlu', material: 'TPU', color_name: 'TPU Transparent',       color_hex: '#D8EEF8', notes: 'TPU 95A' },

  // ─── ELEGOO — Żywica ─────────────────────────────────────────────────────
  { brand: 'Elegoo', material: 'Żywica', color_name: 'Standard Biały',    color_hex: '#F2F0ED', notes: 'Standard Resin' },
  { brand: 'Elegoo', material: 'Żywica', color_name: 'Standard Czarny',   color_hex: '#1A1A1A', notes: 'Standard Resin' },
  { brand: 'Elegoo', material: 'Żywica', color_name: 'Standard Szary',    color_hex: '#888888', notes: 'Standard Resin' },
  { brand: 'Elegoo', material: 'Żywica', color_name: 'Standard Transparentny', color_hex: '#C8E8F0', notes: 'Standard Resin' },
  { brand: 'Elegoo', material: 'Żywica', color_name: 'Standard Niebieski', color_hex: '#1C5FAD', notes: 'Standard Resin' },
  { brand: 'Elegoo', material: 'Żywica', color_name: 'Standard Zielony',  color_hex: '#2E8B1A', notes: 'Standard Resin' },
  { brand: 'Elegoo', material: 'Żywica', color_name: 'Standard Czerwony', color_hex: '#CC2222', notes: 'Standard Resin' },
  { brand: 'Elegoo', material: 'Żywica', color_name: 'Standard Żółty',   color_hex: '#F5C800', notes: 'Standard Resin' },
  { brand: 'Elegoo', material: 'Żywica', color_name: 'Standard Skórny',   color_hex: '#E8C8A0', notes: 'Standard Resin' },
  { brand: 'Elegoo', material: 'Żywica', color_name: 'Standard Pomarańczowy', color_hex: '#E8700A', notes: 'Standard Resin' },
  // Elegoo ABS-like
  { brand: 'Elegoo', material: 'Żywica', color_name: 'ABS-like Biały',    color_hex: '#F2F0ED', notes: 'ABS-Like Resin' },
  { brand: 'Elegoo', material: 'Żywica', color_name: 'ABS-like Czarny',   color_hex: '#1A1A1A', notes: 'ABS-Like Resin' },
  { brand: 'Elegoo', material: 'Żywica', color_name: 'ABS-like Szary',    color_hex: '#888888', notes: 'ABS-Like Resin' },
  { brand: 'Elegoo', material: 'Żywica', color_name: 'ABS-like Transparentny', color_hex: '#C8E8F0', notes: 'ABS-Like Resin' },
  { brand: 'Elegoo', material: 'Żywica', color_name: 'ABS-like Niebieski', color_hex: '#1C5FAD', notes: 'ABS-Like Resin' },
  { brand: 'Elegoo', material: 'Żywica', color_name: 'ABS-like Zielony',  color_hex: '#2E8B1A', notes: 'ABS-Like Resin' },
  // Elegoo Water Washable
  { brand: 'Elegoo', material: 'Żywica', color_name: 'Water Wash Biały',  color_hex: '#F2F0ED', notes: 'Water Washable Resin' },
  { brand: 'Elegoo', material: 'Żywica', color_name: 'Water Wash Czarny', color_hex: '#1A1A1A', notes: 'Water Washable Resin' },
  { brand: 'Elegoo', material: 'Żywica', color_name: 'Water Wash Szary',  color_hex: '#888888', notes: 'Water Washable Resin' },
  { brand: 'Elegoo', material: 'Żywica', color_name: 'Water Wash Transparentny', color_hex: '#C8E8F0', notes: 'Water Washable Resin' },
  { brand: 'Elegoo', material: 'Żywica', color_name: 'Water Wash Zielony', color_hex: '#2E8B1A', notes: 'Water Washable Resin' },
  { brand: 'Elegoo', material: 'Żywica', color_name: 'Water Wash Niebieski', color_hex: '#1C5FAD', notes: 'Water Washable Resin' },
  // Elegoo PLA
  { brand: 'Elegoo', material: 'PLA', color_name: 'Elegoo PLA White',     color_hex: '#F2F0ED', notes: 'PLA Rapid' },
  { brand: 'Elegoo', material: 'PLA', color_name: 'Elegoo PLA Black',     color_hex: '#1A1A1A', notes: 'PLA Rapid' },
  { brand: 'Elegoo', material: 'PLA', color_name: 'Elegoo PLA Grey',      color_hex: '#888888', notes: 'PLA Rapid' },
  { brand: 'Elegoo', material: 'PLA', color_name: 'Elegoo PLA Red',       color_hex: '#CC2222', notes: 'PLA Rapid' },
  { brand: 'Elegoo', material: 'PLA', color_name: 'Elegoo PLA Blue',      color_hex: '#1C5FAD', notes: 'PLA Rapid' },
  { brand: 'Elegoo', material: 'PLA', color_name: 'Elegoo PLA Green',     color_hex: '#2E8B1A', notes: 'PLA Rapid' },
  { brand: 'Elegoo', material: 'PLA', color_name: 'Elegoo PLA Yellow',    color_hex: '#F5C800', notes: 'PLA Rapid' },
  { brand: 'Elegoo', material: 'PLA', color_name: 'Elegoo PLA Orange',    color_hex: '#E8700A', notes: 'PLA Rapid' },
  { brand: 'Elegoo', material: 'PLA', color_name: 'Elegoo PLA Pink',      color_hex: '#E8558A', notes: 'PLA Rapid' },
  { brand: 'Elegoo', material: 'PLA', color_name: 'Elegoo PLA Purple',    color_hex: '#6633CC', notes: 'PLA Rapid' },
]

export const CATALOG_BRANDS = [...new Set(FILAMENT_CATALOG.map(f => f.brand))]
