export const FILAMENT_CATALOG = [
  // ─── BAMBU LAB — PLA Basic ───────────────────────────────────────────────
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Bambu White',            color_hex: '#F2F0ED', notes: 'PLA Basic' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Bambu Black',            color_hex: '#1C1C1C', notes: 'PLA Basic' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Bambu Grey',             color_hex: '#888888', notes: 'PLA Basic' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Bambu Dark Grey',        color_hex: '#3A3A3A', notes: 'PLA Basic' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Bambu Red',              color_hex: '#CC2222', notes: 'PLA Basic' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Bambu Orange',           color_hex: '#E85B0A', notes: 'PLA Basic' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Bambu Yellow',           color_hex: '#F5C800', notes: 'PLA Basic' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Bambu Green',            color_hex: '#2E8B1A', notes: 'PLA Basic' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Bambu Jade Green',       color_hex: '#47B882', notes: 'PLA Basic' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Bambu Blue',             color_hex: '#1C5FAD', notes: 'PLA Basic' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Bambu Navy Blue',        color_hex: '#1A2E6E', notes: 'PLA Basic' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Bambu Purple',           color_hex: '#6633CC', notes: 'PLA Basic' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Bambu Pink',             color_hex: '#E8558A', notes: 'PLA Basic' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Bambu Brown',            color_hex: '#7B4A2D', notes: 'PLA Basic' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Bambu Beige',            color_hex: '#D4C4A0', notes: 'PLA Basic' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Bambu Ivory White',      color_hex: '#F8F4E8', notes: 'PLA Basic' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Bambu Cyan',             color_hex: '#00B4CC', notes: 'PLA Basic' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Bambu Magenta',          color_hex: '#CC2299', notes: 'PLA Basic' },

  // Bambu PLA Matte
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Matte White',            color_hex: '#F0EDE8', notes: 'PLA Matte' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Matte Black',            color_hex: '#222222', notes: 'PLA Matte' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Matte Grey',             color_hex: '#8C8C8C', notes: 'PLA Matte' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Matte Charcoal',         color_hex: '#3E3E3E', notes: 'PLA Matte' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Matte Red',              color_hex: '#C0392B', notes: 'PLA Matte' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Matte Blue',             color_hex: '#2E4FAD', notes: 'PLA Matte' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Matte Green',            color_hex: '#3A7A45', notes: 'PLA Matte' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Matte Yellow',           color_hex: '#D4AE00', notes: 'PLA Matte' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Matte Orange',           color_hex: '#D4591A', notes: 'PLA Matte' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Matte Pink',             color_hex: '#CC5577', notes: 'PLA Matte' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Matte Purple',           color_hex: '#5C3399', notes: 'PLA Matte' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Matte Brown',            color_hex: '#7B4A2D', notes: 'PLA Matte' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Matte Beige',            color_hex: '#D4C4A0', notes: 'PLA Matte' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Matte Navy Blue',        color_hex: '#1A2E6E', notes: 'PLA Matte' },

  // Bambu PLA Silk
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Silk Gold',              color_hex: '#D4A842', notes: 'PLA Silk' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Silk Silver',            color_hex: '#C0C0C8', notes: 'PLA Silk' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Silk Copper',            color_hex: '#B87333', notes: 'PLA Silk' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Silk Red',               color_hex: '#CC2244', notes: 'PLA Silk' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Silk Blue',              color_hex: '#1A44AA', notes: 'PLA Silk' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Silk Green',             color_hex: '#1A7A44', notes: 'PLA Silk' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Silk Purple',            color_hex: '#7733CC', notes: 'PLA Silk' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Silk Rose Gold',         color_hex: '#C9956C', notes: 'PLA Silk' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Silk Bronze',            color_hex: '#8B6914', notes: 'PLA Silk' },

  // Bambu PLA Silk+
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Silk+ Gold',             color_hex: '#D4A842', notes: 'PLA Silk+' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Silk+ Silver',           color_hex: '#C8C8D0', notes: 'PLA Silk+' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Silk+ Copper',           color_hex: '#B87333', notes: 'PLA Silk+' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Silk+ Red',              color_hex: '#CC2244', notes: 'PLA Silk+' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Silk+ Blue',             color_hex: '#1A44AA', notes: 'PLA Silk+' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Silk+ Green',            color_hex: '#1A7A44', notes: 'PLA Silk+' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Silk+ Purple',           color_hex: '#7733CC', notes: 'PLA Silk+' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Silk+ Rose Gold',        color_hex: '#C9956C', notes: 'PLA Silk+' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Silk+ Baby Blue',        color_hex: '#A8D8EA', notes: 'PLA Silk+' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Silk+ Dual Gold-Silver', color_hex: '#C8B060', notes: 'PLA Silk+ Dual' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Silk+ Dual Rainbow',     color_hex: '#AA44AA', notes: 'PLA Silk+ Dual' },

  // Bambu PLA Tough+
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Tough+ White',           color_hex: '#F2F0ED', notes: 'PLA Tough+' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Tough+ Black',           color_hex: '#1C1C1C', notes: 'PLA Tough+' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Tough+ Grey',            color_hex: '#888888', notes: 'PLA Tough+' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Tough+ Red',             color_hex: '#CC2222', notes: 'PLA Tough+' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Tough+ Blue',            color_hex: '#1C5FAD', notes: 'PLA Tough+' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Tough+ Green',           color_hex: '#2E8B1A', notes: 'PLA Tough+' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Tough+ Yellow',          color_hex: '#F5C800', notes: 'PLA Tough+' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Tough+ Orange',          color_hex: '#E85B0A', notes: 'PLA Tough+' },

  // Bambu PLA Sparkle
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Sparkle Gold Glitter',   color_hex: '#D4A842', notes: 'PLA Sparkle' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Sparkle Silver Glitter', color_hex: '#C0C0C8', notes: 'PLA Sparkle' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Sparkle Blue Galaxy',    color_hex: '#1A2A88', notes: 'PLA Sparkle' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Sparkle Red',            color_hex: '#CC2244', notes: 'PLA Sparkle' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Sparkle Purple Galaxy',  color_hex: '#5C2299', notes: 'PLA Sparkle' },

  // Bambu PLA Marble / Metal / Glow
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Marble White',           color_hex: '#E8E8E0', notes: 'PLA Marble' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Marble Grey',            color_hex: '#9A9A9A', notes: 'PLA Marble' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Metal Bronze',           color_hex: '#8B6914', notes: 'PLA Metal' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Metal Silver',           color_hex: '#B0B0B8', notes: 'PLA Metal' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Metal Gold',             color_hex: '#C8A030', notes: 'PLA Metal' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Glow Green',             color_hex: '#A0D060', notes: 'PLA świecący' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Glow Blue',              color_hex: '#80C0F0', notes: 'PLA świecący' },
  { brand: 'Bambu Lab', material: 'PLA', color_name: 'Glow Yellow',            color_hex: '#E0E060', notes: 'PLA świecący' },

  // Bambu PETG Basic
  { brand: 'Bambu Lab', material: 'PETG', color_name: 'PETG White',            color_hex: '#F0EDE8', notes: 'PETG Basic' },
  { brand: 'Bambu Lab', material: 'PETG', color_name: 'PETG Black',            color_hex: '#1A1A1A', notes: 'PETG Basic' },
  { brand: 'Bambu Lab', material: 'PETG', color_name: 'PETG Grey',             color_hex: '#7A7A7A', notes: 'PETG Basic' },
  { brand: 'Bambu Lab', material: 'PETG', color_name: 'PETG Red',              color_hex: '#CC2222', notes: 'PETG Basic' },
  { brand: 'Bambu Lab', material: 'PETG', color_name: 'PETG Blue',             color_hex: '#1C5FAD', notes: 'PETG Basic' },
  { brand: 'Bambu Lab', material: 'PETG', color_name: 'PETG Green',            color_hex: '#2E8B1A', notes: 'PETG Basic' },
  { brand: 'Bambu Lab', material: 'PETG', color_name: 'PETG Yellow',           color_hex: '#F5C800', notes: 'PETG Basic' },
  { brand: 'Bambu Lab', material: 'PETG', color_name: 'PETG Orange',           color_hex: '#E8700A', notes: 'PETG Basic' },
  { brand: 'Bambu Lab', material: 'PETG', color_name: 'PETG Transparent',      color_hex: '#D0E8F0', notes: 'PETG Basic' },
  { brand: 'Bambu Lab', material: 'PETG', color_name: 'PETG Purple',           color_hex: '#6633CC', notes: 'PETG Basic' },
  { brand: 'Bambu Lab', material: 'PETG', color_name: 'PETG Pink',             color_hex: '#E8558A', notes: 'PETG Basic' },
  { brand: 'Bambu Lab', material: 'PETG', color_name: 'PETG Navy Blue',        color_hex: '#1A2E6E', notes: 'PETG Basic' },

  // Bambu PETG HF (High Flow)
  { brand: 'Bambu Lab', material: 'PETG', color_name: 'PETG HF White',         color_hex: '#F0EDE8', notes: 'PETG HF' },
  { brand: 'Bambu Lab', material: 'PETG', color_name: 'PETG HF Black',         color_hex: '#1A1A1A', notes: 'PETG HF' },
  { brand: 'Bambu Lab', material: 'PETG', color_name: 'PETG HF Grey',          color_hex: '#7A7A7A', notes: 'PETG HF' },
  { brand: 'Bambu Lab', material: 'PETG', color_name: 'PETG HF Blue',          color_hex: '#1C5FAD', notes: 'PETG HF' },
  { brand: 'Bambu Lab', material: 'PETG', color_name: 'PETG HF Red',           color_hex: '#CC2222', notes: 'PETG HF' },

  // Bambu ABS
  { brand: 'Bambu Lab', material: 'ABS', color_name: 'ABS White',              color_hex: '#F0EDE8', notes: 'ABS' },
  { brand: 'Bambu Lab', material: 'ABS', color_name: 'ABS Black',              color_hex: '#1A1A1A', notes: 'ABS' },
  { brand: 'Bambu Lab', material: 'ABS', color_name: 'ABS Grey',               color_hex: '#7A7A7A', notes: 'ABS' },
  { brand: 'Bambu Lab', material: 'ABS', color_name: 'ABS Dark Grey',          color_hex: '#3A3A3A', notes: 'ABS' },
  { brand: 'Bambu Lab', material: 'ABS', color_name: 'ABS Red',                color_hex: '#CC2222', notes: 'ABS' },
  { brand: 'Bambu Lab', material: 'ABS', color_name: 'ABS Blue',               color_hex: '#1C5FAD', notes: 'ABS' },
  { brand: 'Bambu Lab', material: 'ABS', color_name: 'ABS Green',              color_hex: '#2E8B1A', notes: 'ABS' },
  { brand: 'Bambu Lab', material: 'ABS', color_name: 'ABS Yellow',             color_hex: '#F5C800', notes: 'ABS' },
  { brand: 'Bambu Lab', material: 'ABS', color_name: 'ABS Orange',             color_hex: '#E85B0A', notes: 'ABS' },
  { brand: 'Bambu Lab', material: 'ABS', color_name: 'ABS Purple',             color_hex: '#6633CC', notes: 'ABS' },
  { brand: 'Bambu Lab', material: 'ABS', color_name: 'ABS Pink',               color_hex: '#E8558A', notes: 'ABS' },

  // Bambu ASA
  { brand: 'Bambu Lab', material: 'ASA', color_name: 'ASA White',              color_hex: '#F2F0ED', notes: 'ASA' },
  { brand: 'Bambu Lab', material: 'ASA', color_name: 'ASA Black',              color_hex: '#1C1C1C', notes: 'ASA' },
  { brand: 'Bambu Lab', material: 'ASA', color_name: 'ASA Grey',               color_hex: '#888888', notes: 'ASA' },
  { brand: 'Bambu Lab', material: 'ASA', color_name: 'ASA Dark Grey',          color_hex: '#3A3A3A', notes: 'ASA' },
  { brand: 'Bambu Lab', material: 'ASA', color_name: 'ASA Red',                color_hex: '#CC2222', notes: 'ASA' },
  { brand: 'Bambu Lab', material: 'ASA', color_name: 'ASA Blue',               color_hex: '#1C5FAD', notes: 'ASA' },
  { brand: 'Bambu Lab', material: 'ASA', color_name: 'ASA Green',              color_hex: '#2E8B1A', notes: 'ASA' },
  { brand: 'Bambu Lab', material: 'ASA', color_name: 'ASA Yellow',             color_hex: '#F5C800', notes: 'ASA' },
  { brand: 'Bambu Lab', material: 'ASA', color_name: 'ASA Orange',             color_hex: '#E85B0A', notes: 'ASA' },
  { brand: 'Bambu Lab', material: 'ASA', color_name: 'ASA Beige',              color_hex: '#D4C4A0', notes: 'ASA' },

  // Bambu TPU 95A
  { brand: 'Bambu Lab', material: 'TPU', color_name: 'TPU White',              color_hex: '#F0EDE8', notes: 'TPU 95A' },
  { brand: 'Bambu Lab', material: 'TPU', color_name: 'TPU Black',              color_hex: '#1A1A1A', notes: 'TPU 95A' },
  { brand: 'Bambu Lab', material: 'TPU', color_name: 'TPU Grey',               color_hex: '#7A7A7A', notes: 'TPU 95A' },
  { brand: 'Bambu Lab', material: 'TPU', color_name: 'TPU Red',                color_hex: '#CC2222', notes: 'TPU 95A' },
  { brand: 'Bambu Lab', material: 'TPU', color_name: 'TPU Blue',               color_hex: '#1C5FAD', notes: 'TPU 95A' },
  { brand: 'Bambu Lab', material: 'TPU', color_name: 'TPU Yellow',             color_hex: '#F5C800', notes: 'TPU 95A' },
  { brand: 'Bambu Lab', material: 'TPU', color_name: 'TPU Orange',             color_hex: '#E85B0A', notes: 'TPU 95A' },
  { brand: 'Bambu Lab', material: 'TPU', color_name: 'TPU Green',              color_hex: '#2E8B1A', notes: 'TPU 95A' },
  { brand: 'Bambu Lab', material: 'TPU', color_name: 'TPU Transparent',        color_hex: '#D8EEF8', notes: 'TPU 95A' },
  { brand: 'Bambu Lab', material: 'TPU', color_name: 'TPU Pink',               color_hex: '#E8558A', notes: 'TPU 95A HF' },
  { brand: 'Bambu Lab', material: 'TPU', color_name: 'TPU Purple',             color_hex: '#6633CC', notes: 'TPU 95A HF' },

  // Bambu PA (Nylon)
  { brand: 'Bambu Lab', material: 'PA', color_name: 'PA White',                color_hex: '#F2F0ED', notes: 'PA6-CF (z CF)' },
  { brand: 'Bambu Lab', material: 'PA', color_name: 'PA Black',                color_hex: '#1C1C1C', notes: 'PA6-CF (z CF)' },
  { brand: 'Bambu Lab', material: 'PA', color_name: 'PA Natural',              color_hex: '#E0D8C8', notes: 'PA (bez CF)' },
  { brand: 'Bambu Lab', material: 'PA', color_name: 'PA Grey',                 color_hex: '#888888', notes: 'PA (bez CF)' },

  // Bambu PLA-CF
  { brand: 'Bambu Lab', material: 'PLA-CF', color_name: 'PLA-CF Black',        color_hex: '#222222', notes: 'PLA z włóknem węglowym' },
  { brand: 'Bambu Lab', material: 'PLA-CF', color_name: 'PLA-CF Charcoal',     color_hex: '#3A3A3A', notes: 'PLA z włóknem węglowym' },
  { brand: 'Bambu Lab', material: 'PLA-CF', color_name: 'PLA-CF Blue',         color_hex: '#1A3A7A', notes: 'PLA z włóknem węglowym' },
  { brand: 'Bambu Lab', material: 'PLA-CF', color_name: 'PLA-CF Red',          color_hex: '#8B1A1A', notes: 'PLA z włóknem węglowym' },

  // Bambu PETG-CF
  { brand: 'Bambu Lab', material: 'PETG-CF', color_name: 'PETG-CF Black',      color_hex: '#222222', notes: 'PETG z włóknem węglowym' },
  { brand: 'Bambu Lab', material: 'PETG-CF', color_name: 'PETG-CF Dark Grey',  color_hex: '#3A3A3A', notes: 'PETG z włóknem węglowym' },

  // Bambu PC (Poliwęglan)
  { brand: 'Bambu Lab', material: 'PC', color_name: 'PC White',                color_hex: '#F2F0ED', notes: 'Poliwęglan' },
  { brand: 'Bambu Lab', material: 'PC', color_name: 'PC Black',                color_hex: '#1C1C1C', notes: 'Poliwęglan' },
  { brand: 'Bambu Lab', material: 'PC', color_name: 'PC Grey',                 color_hex: '#888888', notes: 'Poliwęglan' },
  { brand: 'Bambu Lab', material: 'PC', color_name: 'PC Transparent',          color_hex: '#D8EEF8', notes: 'Poliwęglan transparentny' },

  // ─── SUNLU — PLA+ ────────────────────────────────────────────────────────
  { brand: 'Sunlu', material: 'PLA', color_name: 'Sunlu White',                color_hex: '#F5F2ED', notes: 'PLA+' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Sunlu Black',                color_hex: '#1A1A1A', notes: 'PLA+' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Sunlu Grey',                 color_hex: '#8C8C8C', notes: 'PLA+' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Sunlu Dark Grey',            color_hex: '#404040', notes: 'PLA+' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Sunlu Red',                  color_hex: '#CC2222', notes: 'PLA+' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Sunlu Orange',               color_hex: '#E8700A', notes: 'PLA+' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Sunlu Yellow',               color_hex: '#F5C800', notes: 'PLA+' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Sunlu Green',                color_hex: '#2E8B1A', notes: 'PLA+' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Sunlu Army Green',           color_hex: '#4A6A2A', notes: 'PLA+' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Sunlu Blue',                 color_hex: '#1C5FAD', notes: 'PLA+' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Sunlu Navy Blue',            color_hex: '#1A2E6E', notes: 'PLA+' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Sunlu Purple',               color_hex: '#6633CC', notes: 'PLA+' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Sunlu Pink',                 color_hex: '#E8558A', notes: 'PLA+' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Sunlu Brown',                color_hex: '#7B4A2D', notes: 'PLA+' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Sunlu Skin',                 color_hex: '#E8C8A0', notes: 'PLA+' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Sunlu Transparent',          color_hex: '#D8EEF8', notes: 'PLA+' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Sunlu Glow Green',           color_hex: '#A0D080', notes: 'PLA+ świecący' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Sunlu Glow Blue',            color_hex: '#80C0F0', notes: 'PLA+ świecący' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Sunlu Cyan',                 color_hex: '#00B4CC', notes: 'PLA+' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Sunlu Magenta',              color_hex: '#CC2299', notes: 'PLA+' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Sunlu Beige',                color_hex: '#D4C4A0', notes: 'PLA+' },

  // Sunlu PLA Meta
  { brand: 'Sunlu', material: 'PLA', color_name: 'Meta White',                 color_hex: '#F5F2ED', notes: 'PLA Meta' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Meta Black',                 color_hex: '#1A1A1A', notes: 'PLA Meta' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Meta Grey',                  color_hex: '#8C8C8C', notes: 'PLA Meta' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Meta Red',                   color_hex: '#CC2222', notes: 'PLA Meta' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Meta Blue',                  color_hex: '#1C5FAD', notes: 'PLA Meta' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Meta Green',                 color_hex: '#2E8B1A', notes: 'PLA Meta' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Meta Yellow',                color_hex: '#F5C800', notes: 'PLA Meta' },

  // Sunlu Silk PLA
  { brand: 'Sunlu', material: 'PLA', color_name: 'Silk Gold',                  color_hex: '#D4A842', notes: 'PLA Silk' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Silk Silver',                color_hex: '#C0C0C8', notes: 'PLA Silk' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Silk Copper',                color_hex: '#B87333', notes: 'PLA Silk' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Silk Red',                   color_hex: '#CC2244', notes: 'PLA Silk' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Silk Blue',                  color_hex: '#1A44AA', notes: 'PLA Silk' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Silk Purple',                color_hex: '#6633CC', notes: 'PLA Silk' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Silk Green',                 color_hex: '#1A7A44', notes: 'PLA Silk' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Silk Rose Gold',             color_hex: '#C9956C', notes: 'PLA Silk' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Silk Dual Rainbow',          color_hex: '#AA44AA', notes: 'PLA Silk Dual' },
  { brand: 'Sunlu', material: 'PLA', color_name: 'Silk Dual Gold-Silver',      color_hex: '#C8B060', notes: 'PLA Silk Dual' },

  // Sunlu PETG
  { brand: 'Sunlu', material: 'PETG', color_name: 'PETG White',                color_hex: '#F0EDE8', notes: 'PETG' },
  { brand: 'Sunlu', material: 'PETG', color_name: 'PETG Black',                color_hex: '#1A1A1A', notes: 'PETG' },
  { brand: 'Sunlu', material: 'PETG', color_name: 'PETG Grey',                 color_hex: '#7A7A7A', notes: 'PETG' },
  { brand: 'Sunlu', material: 'PETG', color_name: 'PETG Red',                  color_hex: '#CC2222', notes: 'PETG' },
  { brand: 'Sunlu', material: 'PETG', color_name: 'PETG Blue',                 color_hex: '#1C5FAD', notes: 'PETG' },
  { brand: 'Sunlu', material: 'PETG', color_name: 'PETG Green',                color_hex: '#2E8B1A', notes: 'PETG' },
  { brand: 'Sunlu', material: 'PETG', color_name: 'PETG Yellow',               color_hex: '#F5C800', notes: 'PETG' },
  { brand: 'Sunlu', material: 'PETG', color_name: 'PETG Orange',               color_hex: '#E8700A', notes: 'PETG' },
  { brand: 'Sunlu', material: 'PETG', color_name: 'PETG Transparent',          color_hex: '#D0E8F0', notes: 'PETG' },
  { brand: 'Sunlu', material: 'PETG', color_name: 'PETG Purple',               color_hex: '#6633CC', notes: 'PETG' },
  { brand: 'Sunlu', material: 'PETG', color_name: 'PETG Pink',                 color_hex: '#E8558A', notes: 'PETG' },

  // Sunlu PETG+
  { brand: 'Sunlu', material: 'PETG', color_name: 'PETG+ White',               color_hex: '#F0EDE8', notes: 'PETG+' },
  { brand: 'Sunlu', material: 'PETG', color_name: 'PETG+ Black',               color_hex: '#1A1A1A', notes: 'PETG+' },
  { brand: 'Sunlu', material: 'PETG', color_name: 'PETG+ Grey',                color_hex: '#7A7A7A', notes: 'PETG+' },
  { brand: 'Sunlu', material: 'PETG', color_name: 'PETG+ Red',                 color_hex: '#CC2222', notes: 'PETG+' },
  { brand: 'Sunlu', material: 'PETG', color_name: 'PETG+ Blue',                color_hex: '#1C5FAD', notes: 'PETG+' },
  { brand: 'Sunlu', material: 'PETG', color_name: 'PETG+ Green',               color_hex: '#2E8B1A', notes: 'PETG+' },
  { brand: 'Sunlu', material: 'PETG', color_name: 'PETG+ Yellow',              color_hex: '#F5C800', notes: 'PETG+' },

  // Sunlu ABS
  { brand: 'Sunlu', material: 'ABS', color_name: 'ABS White',                  color_hex: '#F0EDE8', notes: 'ABS' },
  { brand: 'Sunlu', material: 'ABS', color_name: 'ABS Black',                  color_hex: '#1A1A1A', notes: 'ABS' },
  { brand: 'Sunlu', material: 'ABS', color_name: 'ABS Grey',                   color_hex: '#7A7A7A', notes: 'ABS' },
  { brand: 'Sunlu', material: 'ABS', color_name: 'ABS Red',                    color_hex: '#CC2222', notes: 'ABS' },
  { brand: 'Sunlu', material: 'ABS', color_name: 'ABS Blue',                   color_hex: '#1C5FAD', notes: 'ABS' },
  { brand: 'Sunlu', material: 'ABS', color_name: 'ABS Green',                  color_hex: '#2E8B1A', notes: 'ABS' },
  { brand: 'Sunlu', material: 'ABS', color_name: 'ABS Yellow',                 color_hex: '#F5C800', notes: 'ABS' },
  { brand: 'Sunlu', material: 'ABS', color_name: 'ABS Orange',                 color_hex: '#E8700A', notes: 'ABS' },

  // Sunlu ASA
  { brand: 'Sunlu', material: 'ASA', color_name: 'ASA White',                  color_hex: '#F2F0ED', notes: 'ASA' },
  { brand: 'Sunlu', material: 'ASA', color_name: 'ASA Black',                  color_hex: '#1C1C1C', notes: 'ASA' },
  { brand: 'Sunlu', material: 'ASA', color_name: 'ASA Grey',                   color_hex: '#888888', notes: 'ASA' },
  { brand: 'Sunlu', material: 'ASA', color_name: 'ASA Red',                    color_hex: '#CC2222', notes: 'ASA' },
  { brand: 'Sunlu', material: 'ASA', color_name: 'ASA Blue',                   color_hex: '#1C5FAD', notes: 'ASA' },
  { brand: 'Sunlu', material: 'ASA', color_name: 'ASA Green',                  color_hex: '#2E8B1A', notes: 'ASA' },

  // Sunlu TPU
  { brand: 'Sunlu', material: 'TPU', color_name: 'TPU White',                  color_hex: '#F0EDE8', notes: 'TPU 95A' },
  { brand: 'Sunlu', material: 'TPU', color_name: 'TPU Black',                  color_hex: '#1A1A1A', notes: 'TPU 95A' },
  { brand: 'Sunlu', material: 'TPU', color_name: 'TPU Grey',                   color_hex: '#7A7A7A', notes: 'TPU 95A' },
  { brand: 'Sunlu', material: 'TPU', color_name: 'TPU Red',                    color_hex: '#CC2222', notes: 'TPU 95A' },
  { brand: 'Sunlu', material: 'TPU', color_name: 'TPU Blue',                   color_hex: '#1C5FAD', notes: 'TPU 95A' },
  { brand: 'Sunlu', material: 'TPU', color_name: 'TPU Yellow',                 color_hex: '#F5C800', notes: 'TPU 95A' },
  { brand: 'Sunlu', material: 'TPU', color_name: 'TPU Transparent',            color_hex: '#D8EEF8', notes: 'TPU 95A' },
  { brand: 'Sunlu', material: 'TPU', color_name: 'TPU Green',                  color_hex: '#2E8B1A', notes: 'TPU 95A' },
  { brand: 'Sunlu', material: 'TPU', color_name: 'TPU Orange',                 color_hex: '#E85B0A', notes: 'TPU 95A' },
  { brand: 'Sunlu', material: 'TPU', color_name: 'TPU Pink',                   color_hex: '#E8558A', notes: 'TPU 95A' },

  // Sunlu HIPS
  { brand: 'Sunlu', material: 'HIPS', color_name: 'HIPS White',                color_hex: '#F2F0ED', notes: 'HIPS' },
  { brand: 'Sunlu', material: 'HIPS', color_name: 'HIPS Black',                color_hex: '#1C1C1C', notes: 'HIPS' },
  { brand: 'Sunlu', material: 'HIPS', color_name: 'HIPS Natural',              color_hex: '#E8E0D0', notes: 'HIPS' },

  // Sunlu PVA (materiał podporowy)
  { brand: 'Sunlu', material: 'PVA', color_name: 'PVA Natural',                color_hex: '#F0ECD8', notes: 'PVA — rozpuszczalny w wodzie' },

  // ─── ELEGOO — Żywica ─────────────────────────────────────────────────────
  { brand: 'Elegoo', material: 'Żywica', color_name: 'Standard Biały',         color_hex: '#F2F0ED', notes: 'Standard Resin' },
  { brand: 'Elegoo', material: 'Żywica', color_name: 'Standard Czarny',        color_hex: '#1A1A1A', notes: 'Standard Resin' },
  { brand: 'Elegoo', material: 'Żywica', color_name: 'Standard Szary',         color_hex: '#888888', notes: 'Standard Resin' },
  { brand: 'Elegoo', material: 'Żywica', color_name: 'Standard Transparentny', color_hex: '#C8E8F0', notes: 'Standard Resin' },
  { brand: 'Elegoo', material: 'Żywica', color_name: 'Standard Niebieski',     color_hex: '#1C5FAD', notes: 'Standard Resin' },
  { brand: 'Elegoo', material: 'Żywica', color_name: 'Standard Zielony',       color_hex: '#2E8B1A', notes: 'Standard Resin' },
  { brand: 'Elegoo', material: 'Żywica', color_name: 'Standard Czerwony',      color_hex: '#CC2222', notes: 'Standard Resin' },
  { brand: 'Elegoo', material: 'Żywica', color_name: 'Standard Żółty',         color_hex: '#F5C800', notes: 'Standard Resin' },
  { brand: 'Elegoo', material: 'Żywica', color_name: 'Standard Skórny',        color_hex: '#E8C8A0', notes: 'Standard Resin' },
  { brand: 'Elegoo', material: 'Żywica', color_name: 'Standard Pomarańczowy',  color_hex: '#E8700A', notes: 'Standard Resin' },
  { brand: 'Elegoo', material: 'Żywica', color_name: 'Standard Fioletowy',     color_hex: '#6633CC', notes: 'Standard Resin' },
  { brand: 'Elegoo', material: 'Żywica', color_name: 'Standard Różowy',        color_hex: '#E8558A', notes: 'Standard Resin' },
  { brand: 'Elegoo', material: 'Żywica', color_name: 'Standard Ciemny Szary',  color_hex: '#3A3A3A', notes: 'Standard Resin' },

  // Elegoo ABS-like
  { brand: 'Elegoo', material: 'Żywica', color_name: 'ABS-like Biały',         color_hex: '#F2F0ED', notes: 'ABS-Like Resin' },
  { brand: 'Elegoo', material: 'Żywica', color_name: 'ABS-like Czarny',        color_hex: '#1A1A1A', notes: 'ABS-Like Resin' },
  { brand: 'Elegoo', material: 'Żywica', color_name: 'ABS-like Szary',         color_hex: '#888888', notes: 'ABS-Like Resin' },
  { brand: 'Elegoo', material: 'Żywica', color_name: 'ABS-like Transparentny', color_hex: '#C8E8F0', notes: 'ABS-Like Resin' },
  { brand: 'Elegoo', material: 'Żywica', color_name: 'ABS-like Niebieski',     color_hex: '#1C5FAD', notes: 'ABS-Like Resin' },
  { brand: 'Elegoo', material: 'Żywica', color_name: 'ABS-like Zielony',       color_hex: '#2E8B1A', notes: 'ABS-Like Resin' },
  { brand: 'Elegoo', material: 'Żywica', color_name: 'ABS-like Czerwony',      color_hex: '#CC2222', notes: 'ABS-Like Resin' },
  { brand: 'Elegoo', material: 'Żywica', color_name: 'ABS-like Żółty',         color_hex: '#F5C800', notes: 'ABS-Like Resin' },

  // Elegoo ABS-like Pro
  { brand: 'Elegoo', material: 'Żywica', color_name: 'ABS-like Pro Biały',     color_hex: '#F5F2ED', notes: 'ABS-Like Pro Resin' },
  { brand: 'Elegoo', material: 'Żywica', color_name: 'ABS-like Pro Czarny',    color_hex: '#1A1A1A', notes: 'ABS-Like Pro Resin' },
  { brand: 'Elegoo', material: 'Żywica', color_name: 'ABS-like Pro Szary',     color_hex: '#888888', notes: 'ABS-Like Pro Resin' },

  // Elegoo Water Washable
  { brand: 'Elegoo', material: 'Żywica', color_name: 'Water Wash Biały',       color_hex: '#F2F0ED', notes: 'Water Washable Resin' },
  { brand: 'Elegoo', material: 'Żywica', color_name: 'Water Wash Czarny',      color_hex: '#1A1A1A', notes: 'Water Washable Resin' },
  { brand: 'Elegoo', material: 'Żywica', color_name: 'Water Wash Szary',       color_hex: '#888888', notes: 'Water Washable Resin' },
  { brand: 'Elegoo', material: 'Żywica', color_name: 'Water Wash Transparentny', color_hex: '#C8E8F0', notes: 'Water Washable Resin' },
  { brand: 'Elegoo', material: 'Żywica', color_name: 'Water Wash Zielony',     color_hex: '#2E8B1A', notes: 'Water Washable Resin' },
  { brand: 'Elegoo', material: 'Żywica', color_name: 'Water Wash Niebieski',   color_hex: '#1C5FAD', notes: 'Water Washable Resin' },
  { brand: 'Elegoo', material: 'Żywica', color_name: 'Water Wash Czerwony',    color_hex: '#CC2222', notes: 'Water Washable Resin' },
  { brand: 'Elegoo', material: 'Żywica', color_name: 'Water Wash Fioletowy',   color_hex: '#6633CC', notes: 'Water Washable Resin' },
  { brand: 'Elegoo', material: 'Żywica', color_name: 'Water Wash Żółty',       color_hex: '#F5C800', notes: 'Water Washable Resin' },

  // Elegoo 8K / Matte Resin
  { brand: 'Elegoo', material: 'Żywica', color_name: '8K Biały',               color_hex: '#F5F2ED', notes: '8K Resin' },
  { brand: 'Elegoo', material: 'Żywica', color_name: '8K Szary',               color_hex: '#888888', notes: '8K Resin' },
  { brand: 'Elegoo', material: 'Żywica', color_name: '8K Czarny',              color_hex: '#1A1A1A', notes: '8K Resin' },
  { brand: 'Elegoo', material: 'Żywica', color_name: 'Matte Biały',            color_hex: '#F0EDE8', notes: 'Matte Resin' },
  { brand: 'Elegoo', material: 'Żywica', color_name: 'Matte Szary',            color_hex: '#8C8C8C', notes: 'Matte Resin' },
  { brand: 'Elegoo', material: 'Żywica', color_name: 'Matte Czarny',           color_hex: '#222222', notes: 'Matte Resin' },

  // Elegoo PLA Rapid
  { brand: 'Elegoo', material: 'PLA', color_name: 'Elegoo PLA White',          color_hex: '#F2F0ED', notes: 'PLA Rapid' },
  { brand: 'Elegoo', material: 'PLA', color_name: 'Elegoo PLA Black',          color_hex: '#1A1A1A', notes: 'PLA Rapid' },
  { brand: 'Elegoo', material: 'PLA', color_name: 'Elegoo PLA Grey',           color_hex: '#888888', notes: 'PLA Rapid' },
  { brand: 'Elegoo', material: 'PLA', color_name: 'Elegoo PLA Red',            color_hex: '#CC2222', notes: 'PLA Rapid' },
  { brand: 'Elegoo', material: 'PLA', color_name: 'Elegoo PLA Blue',           color_hex: '#1C5FAD', notes: 'PLA Rapid' },
  { brand: 'Elegoo', material: 'PLA', color_name: 'Elegoo PLA Green',          color_hex: '#2E8B1A', notes: 'PLA Rapid' },
  { brand: 'Elegoo', material: 'PLA', color_name: 'Elegoo PLA Yellow',         color_hex: '#F5C800', notes: 'PLA Rapid' },
  { brand: 'Elegoo', material: 'PLA', color_name: 'Elegoo PLA Orange',         color_hex: '#E8700A', notes: 'PLA Rapid' },
  { brand: 'Elegoo', material: 'PLA', color_name: 'Elegoo PLA Pink',           color_hex: '#E8558A', notes: 'PLA Rapid' },
  { brand: 'Elegoo', material: 'PLA', color_name: 'Elegoo PLA Purple',         color_hex: '#6633CC', notes: 'PLA Rapid' },
  { brand: 'Elegoo', material: 'PLA', color_name: 'Elegoo PLA Cyan',           color_hex: '#00B4CC', notes: 'PLA Rapid' },
  { brand: 'Elegoo', material: 'PLA', color_name: 'Elegoo PLA Navy',           color_hex: '#1A2E6E', notes: 'PLA Rapid' },

  // ─── ESUN ─────────────────────────────────────────────────────────────────
  { brand: 'eSUN', material: 'PLA', color_name: 'eSUN PLA+ Biały',             color_hex: '#F5F2ED', notes: 'PLA+' },
  { brand: 'eSUN', material: 'PLA', color_name: 'eSUN PLA+ Czarny',            color_hex: '#1A1A1A', notes: 'PLA+' },
  { brand: 'eSUN', material: 'PLA', color_name: 'eSUN PLA+ Szary',             color_hex: '#8C8C8C', notes: 'PLA+' },
  { brand: 'eSUN', material: 'PLA', color_name: 'eSUN PLA+ Czerwony',          color_hex: '#CC2222', notes: 'PLA+' },
  { brand: 'eSUN', material: 'PLA', color_name: 'eSUN PLA+ Niebieski',         color_hex: '#1C5FAD', notes: 'PLA+' },
  { brand: 'eSUN', material: 'PLA', color_name: 'eSUN PLA+ Zielony',           color_hex: '#2E8B1A', notes: 'PLA+' },
  { brand: 'eSUN', material: 'PLA', color_name: 'eSUN PLA+ Żółty',             color_hex: '#F5C800', notes: 'PLA+' },
  { brand: 'eSUN', material: 'PLA', color_name: 'eSUN PLA+ Pomarańczowy',      color_hex: '#E8700A', notes: 'PLA+' },
  { brand: 'eSUN', material: 'PLA', color_name: 'eSUN PLA+ Fioletowy',         color_hex: '#6633CC', notes: 'PLA+' },
  { brand: 'eSUN', material: 'PLA', color_name: 'eSUN PLA+ Różowy',            color_hex: '#E8558A', notes: 'PLA+' },
  { brand: 'eSUN', material: 'PLA', color_name: 'eSUN PLA+ Brązowy',           color_hex: '#7B4A2D', notes: 'PLA+' },
  { brand: 'eSUN', material: 'PLA', color_name: 'eSUN PLA+ Skin',              color_hex: '#E8C8A0', notes: 'PLA+' },
  { brand: 'eSUN', material: 'PLA', color_name: 'eSUN PLA+ Marmur',            color_hex: '#E8E8E0', notes: 'PLA+ Marble' },
  // eSUN PETG
  { brand: 'eSUN', material: 'PETG', color_name: 'eSUN PETG Biały',            color_hex: '#F0EDE8', notes: 'PETG' },
  { brand: 'eSUN', material: 'PETG', color_name: 'eSUN PETG Czarny',           color_hex: '#1A1A1A', notes: 'PETG' },
  { brand: 'eSUN', material: 'PETG', color_name: 'eSUN PETG Szary',            color_hex: '#7A7A7A', notes: 'PETG' },
  { brand: 'eSUN', material: 'PETG', color_name: 'eSUN PETG Czerwony',         color_hex: '#CC2222', notes: 'PETG' },
  { brand: 'eSUN', material: 'PETG', color_name: 'eSUN PETG Niebieski',        color_hex: '#1C5FAD', notes: 'PETG' },
  { brand: 'eSUN', material: 'PETG', color_name: 'eSUN PETG Transparentny',    color_hex: '#D0E8F0', notes: 'PETG' },
  // eSUN ABS+
  { brand: 'eSUN', material: 'ABS', color_name: 'eSUN ABS+ Biały',             color_hex: '#F0EDE8', notes: 'ABS+' },
  { brand: 'eSUN', material: 'ABS', color_name: 'eSUN ABS+ Czarny',            color_hex: '#1A1A1A', notes: 'ABS+' },
  { brand: 'eSUN', material: 'ABS', color_name: 'eSUN ABS+ Szary',             color_hex: '#7A7A7A', notes: 'ABS+' },
  { brand: 'eSUN', material: 'ABS', color_name: 'eSUN ABS+ Czerwony',          color_hex: '#CC2222', notes: 'ABS+' },
  { brand: 'eSUN', material: 'ABS', color_name: 'eSUN ABS+ Niebieski',         color_hex: '#1C5FAD', notes: 'ABS+' },
  // eSUN TPU
  { brand: 'eSUN', material: 'TPU', color_name: 'eSUN TPU Biały',              color_hex: '#F0EDE8', notes: 'TPU 95A' },
  { brand: 'eSUN', material: 'TPU', color_name: 'eSUN TPU Czarny',             color_hex: '#1A1A1A', notes: 'TPU 95A' },
  { brand: 'eSUN', material: 'TPU', color_name: 'eSUN TPU Czerwony',           color_hex: '#CC2222', notes: 'TPU 95A' },
  { brand: 'eSUN', material: 'TPU', color_name: 'eSUN TPU Transparentny',      color_hex: '#D8EEF8', notes: 'TPU 95A' },
  // eSUN ePA (Nylon)
  { brand: 'eSUN', material: 'PA', color_name: 'eSUN ePA Naturalny',           color_hex: '#E8E0D0', notes: 'ePA (Nylon)' },
  { brand: 'eSUN', material: 'PA', color_name: 'eSUN ePA Czarny',              color_hex: '#1A1A1A', notes: 'ePA (Nylon)' },
  // eSUN PVA
  { brand: 'eSUN', material: 'PVA', color_name: 'eSUN PVA Naturalny',          color_hex: '#F0ECD8', notes: 'PVA — podporowy' },

  // ─── FIBERLOGY ────────────────────────────────────────────────────────────
  { brand: 'Fiberlogy', material: 'PLA', color_name: 'FiberFlex Biały',        color_hex: '#F5F2ED', notes: 'PLA' },
  { brand: 'Fiberlogy', material: 'PLA', color_name: 'FiberFlex Czarny',       color_hex: '#1A1A1A', notes: 'PLA' },
  { brand: 'Fiberlogy', material: 'PLA', color_name: 'FiberFlex Szary',        color_hex: '#8C8C8C', notes: 'PLA' },
  { brand: 'Fiberlogy', material: 'PLA', color_name: 'FiberFlex Czerwony',     color_hex: '#CC2222', notes: 'PLA' },
  { brand: 'Fiberlogy', material: 'PLA', color_name: 'FiberFlex Niebieski',    color_hex: '#1C5FAD', notes: 'PLA' },
  { brand: 'Fiberlogy', material: 'PLA', color_name: 'FiberFlex Zielony',      color_hex: '#2E8B1A', notes: 'PLA' },
  { brand: 'Fiberlogy', material: 'PLA', color_name: 'FiberFlex Żółty',        color_hex: '#F5C800', notes: 'PLA' },
  { brand: 'Fiberlogy', material: 'PLA', color_name: 'FiberFlex Pomarańczowy', color_hex: '#E8700A', notes: 'PLA' },
  { brand: 'Fiberlogy', material: 'PETG', color_name: 'Fiberlogy PETG Biały',  color_hex: '#F0EDE8', notes: 'PETG' },
  { brand: 'Fiberlogy', material: 'PETG', color_name: 'Fiberlogy PETG Czarny', color_hex: '#1A1A1A', notes: 'PETG' },
  { brand: 'Fiberlogy', material: 'PETG', color_name: 'Fiberlogy PETG Szary',  color_hex: '#7A7A7A', notes: 'PETG' },
  { brand: 'Fiberlogy', material: 'PETG', color_name: 'Fiberlogy PETG Czerwony', color_hex: '#CC2222', notes: 'PETG' },
  { brand: 'Fiberlogy', material: 'PETG', color_name: 'Fiberlogy PETG Niebieski', color_hex: '#1C5FAD', notes: 'PETG' },
  { brand: 'Fiberlogy', material: 'ASA', color_name: 'Fiberlogy ASA Biały',    color_hex: '#F2F0ED', notes: 'ASA' },
  { brand: 'Fiberlogy', material: 'ASA', color_name: 'Fiberlogy ASA Czarny',   color_hex: '#1C1C1C', notes: 'ASA' },
  { brand: 'Fiberlogy', material: 'ASA', color_name: 'Fiberlogy ASA Szary',    color_hex: '#888888', notes: 'ASA' },
  { brand: 'Fiberlogy', material: 'TPU', color_name: 'Fiberlogy TPU Biały',    color_hex: '#F0EDE8', notes: 'TPU 40D' },
  { brand: 'Fiberlogy', material: 'TPU', color_name: 'Fiberlogy TPU Czarny',   color_hex: '#1A1A1A', notes: 'TPU 40D' },
  { brand: 'Fiberlogy', material: 'TPU', color_name: 'Fiberlogy TPU Transparentny', color_hex: '#D8EEF8', notes: 'TPU 40D' },
  { brand: 'Fiberlogy', material: 'PA', color_name: 'Fiberlogy PA12-CF Czarny', color_hex: '#222222', notes: 'PA12-CF (nylon z CF)' },
  { brand: 'Fiberlogy', material: 'PA', color_name: 'Fiberlogy PA Naturalny',  color_hex: '#E8E0D0', notes: 'PA12 (Nylon)' },
]

export const CATALOG_BRANDS = [...new Set(FILAMENT_CATALOG.map(f => f.brand))]
